export const OPEN_CHAT = 'OPEN_CHAT';
export const CLOSE_CHAT = 'CLOSE_CHAT';

export const CHANGE_REPLY = 'CHANGE_REPLY';
export const SET_CONFIG = 'SET_CONFIG';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

export const INIT_WITH_SESSION = 'INIT_WITH_SESSION';
export const INIT_WITH_SESSION_SUCCESS = 'INIT_WITH_SESSION_SUCCESS';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';